# Generated by Django 5.0.1 on 2024-04-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialAPP', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='imagen',
        ),
    ]
