# Generated by Django 5.0.1 on 2024-05-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialAPP', '0006_remove_profile_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
