# Generated by Django 5.0.1 on 2024-05-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialAPP', '0007_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
