# Generated by Django 5.0.1 on 2024-05-15 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialAPP', '0009_remove_profile_profile_picture_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField()),
                ('source', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='jsonPost',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numComments', models.IntegerField()),
                ('numReactions', models.IntegerField(blank=True, null=True)),
                ('numShares', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('person_name', models.CharField(max_length=256)),
                ('person_description', models.TextField()),
                ('person_link', models.URLField()),
                ('postedAt', models.DateTimeField()),
                ('urn', models.CharField(max_length=256)),
                ('embeddedObject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socialAPP.embeddedobject')),
            ],
        ),
    ]
