# Generated by Django 5.0.1 on 2024-05-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialAPP', '0010_embeddedobject_jsonpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonpost',
            name='embeddedObject',
        ),
        migrations.DeleteModel(
            name='EmbeddedObject',
        ),
        migrations.DeleteModel(
            name='jsonPost',
        ),
    ]
