# Generated by Django 5.0.1 on 2024-05-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialAPP', '0011_remove_jsonpost_embeddedobject_delete_embeddedobject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.URLField()),
                ('soure', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('reactionType', models.CharField(max_length=256)),
                ('personName', models.CharField(max_length=256)),
                ('personLink', models.URLField()),
                ('personDescription', models.TextField()),
            ],
        ),
    ]
