# Generated by Django 5.0.1 on 2024-05-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialAPP', '0012_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
